version: '3'
services: 
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
    app:
        container_name: CBC-Api
        restart: always
        build: ./api
        ports: 
            - '6666:6666'
        links: 
            - mongo
    front:
        container_name: CBC-Front-React
        restart: always
        build: ./front
        ports:
            - '80:3000'
        links: 
            - app
        environment:
            NODE_ENV: "development"
            CHOKIDAR_USEPOLLING: "true"
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: "admin"
            ME_CONFIG_BASICAUTH_PASSWORD: "admin"
        depends_on:
            - mongo