version: '3'
services: 
    app:
        container_name: CBC-Api
        restart: always
        build: .
        ports: 
            - '80:3001'
        links: 
            - mongodb
    mongodb:
        container_name: mongodb
        image: mongo
        ports: 
            - '27017:27017'